[package]
name = "hyperdesk-desktop"
version = "1.0.0"
description = "HyperDesk Ultra Low Latency Remote Desktop App"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "clipboard-all", "notification-all", "dialog-all" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
